param(
    [string]$RootPath = ".",
    [string]$BaselinePath = "cmake/code_structure_baseline.txt",
    [string]$OutputPath = "",
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path -LiteralPath $RootPath).Path
$baselineFile = Join-Path $root $BaselinePath
$baseline = @{}
if (Test-Path -LiteralPath $baselineFile) {
    foreach ($line in Get-Content -LiteralPath $baselineFile) {
        if ($line.Trim().Length -eq 0 -or $line.TrimStart().StartsWith("#")) {
            continue
        }
        $parts = $line.Split("|", 2)
        if ($parts.Count -ne 2) {
            throw "Invalid code structure baseline entry: $line"
        }
        $baseline[$parts[0]] = [int]$parts[1]
    }
}

$sourceRoot = Join-Path $root "src"
$rows = @()
foreach ($file in Get-ChildItem -LiteralPath $sourceRoot -Recurse -File) {
    if ($file.Extension -notin @(".cpp", ".h", ".qml")) {
        continue
    }
    $relative = $file.FullName.Substring($root.Length + 1).Replace([char]92, [char]47)
    $lines = (Get-Content -LiteralPath $file.FullName).Count
    $limit = if ($file.Extension -eq ".h") { 400 } elseif ($file.Extension -eq ".qml") { 1000 } else { 1200 }
    $rows += [pscustomobject]@{ Path = $relative; Lines = $lines; Limit = $limit; OverBudget = $lines -gt $limit }
}

$dependencyRules = @(
    @{ Prefix = "src/core/"; Pattern = '^\s*#\s*include\s*[<"](application|domain|infrastructure|platform|ui)/' },
    @{ Prefix = "src/domain/"; Pattern = '^\s*#\s*include\s*[<"](application|infrastructure|platform|ui)/' },
    @{ Prefix = "src/infrastructure/"; Pattern = '^\s*#\s*include\s*[<"](application|ui)/' }
)
$dependencyViolations = @()
foreach ($rule in $dependencyRules) {
    $directory = Join-Path $root $rule.Prefix
    foreach ($match in Get-ChildItem -LiteralPath $directory -Recurse -File -Include *.cpp, *.h |
        Select-String -Pattern $rule.Pattern) {
        $relative = $match.Path.Substring($root.Length + 1).Replace([char]92, [char]47)
        $dependencyViolations += "$relative`:$($match.LineNumber): $($match.Line.Trim())"
    }
}

$budgetViolations = @()
foreach ($row in $rows | Where-Object OverBudget) {
    if (-not $baseline.ContainsKey($row.Path) -or $row.Lines -gt $baseline[$row.Path]) {
        $budgetViolations += "$($row.Path): $($row.Lines) lines (budget $($row.Limit), baseline $($baseline[$row.Path]))"
    }
}

$report = @(
    "# Ztermy code health report",
    "",
    "Generated by ``scripts/code_health_report.ps1`` from the current source tree.",
    "",
    "## Largest source files",
    "",
    "| Lines | Budget | Path |",
    "|---:|---:|---|"
)
foreach ($row in $rows | Sort-Object Lines -Descending | Select-Object -First 25) {
    $report += "| $($row.Lines) | $($row.Limit) | ``$($row.Path)`` |"
}
$report += @(
    "",
    "## Budget debt",
    "",
    "Existing over-budget files: $(($rows | Where-Object OverBudget).Count). The baseline is ratcheted: existing files may shrink but cannot grow, and new files must stay within budget.",
    "",
    "## Dependency direction",
    "",
    $(if ($dependencyViolations.Count -eq 0) { "No direct include-direction violations found for core, domain, or infrastructure layers." } else { $dependencyViolations -join "`n" }),
    "",
    "## Gate result",
    "",
    $(if ($budgetViolations.Count -eq 0 -and $dependencyViolations.Count -eq 0) { "PASS" } else { "FAIL" })
)

if ($OutputPath.Length -gt 0) {
    $destination = if ([IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $root $OutputPath }
    $parent = Split-Path -Parent $destination
    if ($parent.Length -gt 0) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    Set-Content -LiteralPath $destination -Value $report -Encoding utf8
}
$report -join "`n"

if ($Check -and ($budgetViolations.Count -gt 0 -or $dependencyViolations.Count -gt 0)) {
    if ($budgetViolations.Count -gt 0) {
        Write-Error ("Code size budget regressions:`n" + ($budgetViolations -join "`n"))
    }
    if ($dependencyViolations.Count -gt 0) {
        Write-Error ("Dependency direction violations:`n" + ($dependencyViolations -join "`n"))
    }
    exit 1
}
