cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED LAUNCHER OR NOT EXISTS "${LAUNCHER}")
    message(FATAL_ERROR "LAUNCHER must name the built ztermy performance launcher")
endif()
if(NOT DEFINED OUTPUT_ROOT)
    message(FATAL_ERROR "OUTPUT_ROOT is required")
endif()
if(NOT DEFINED RUN_COUNT)
    set(RUN_COUNT 5)
endif()
if(RUN_COUNT LESS 1 OR RUN_COUNT GREATER 21)
    message(FATAL_ERROR "RUN_COUNT must be between 1 and 21")
endif()

set(backdrops acrylic mica micaAlt transparent opaque)

foreach(run RANGE 1 ${RUN_COUNT})
    foreach(backdrop IN LISTS backdrops)
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E env
                    "ZTERMY_PERFORMANCE_BACKDROP=${backdrop}"
                    "ZTERMY_PERFORMANCE_RUN_ID=${run}"
                    "QSG_INFO=1"
                    "QT_DISABLE_SHADER_DISK_CACHE=1"
                    "${LAUNCHER}"
            RESULT_VARIABLE terminal_result
        )
        if(NOT terminal_result EQUAL 0)
            message(FATAL_ERROR "Terminal performance benchmark failed for ${backdrop} run ${run}: ${terminal_result}")
        endif()

        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E env
                    "ZTERMY_PERFORMANCE_BACKDROP=${backdrop}"
                    "ZTERMY_PERFORMANCE_RUN_ID=${run}"
                    "QSG_INFO=1"
                    "QSG_RENDER_TIMING=1"
                    "QT_DISABLE_SHADER_DISK_CACHE=1"
                    "${LAUNCHER}" --ui
            RESULT_VARIABLE ui_result
        )
        if(NOT ui_result EQUAL 0)
            message(FATAL_ERROR "UI performance benchmark failed for ${backdrop} run ${run}: ${ui_result}")
        endif()
    endforeach()
endforeach()

function(read_json_value output json)
    string(JSON value ERROR_VARIABLE error GET "${json}" ${ARGN})
    if(error)
        message(FATAL_ERROR "Could not read JSON path '${ARGN}': ${error}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(median output)
    set(values ${ARGN})
    list(SORT values COMPARE NATURAL ORDER ASCENDING)
    list(LENGTH values length)
    math(EXPR middle "${length} / 2")
    list(GET values ${middle} value)
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

set(report "${OUTPUT_ROOT}/composition-performance-matrix.md")
file(WRITE "${report}"
    "# Composition performance matrix\n\n"
    "Generated by the static Release benchmark on an interactive Windows desktop. "
    "Each value is the median of ${RUN_COUNT} warm runs with an identical workload.\n\n"
    "| Backdrop | Alpha bits | DWM type | Terminal ms | Terminal gap ms | Upload MiB | UI load ms | Workbench open ms | UI stream ms | UI gap ms |\n"
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n"
)
string(CONCAT raw_rows
    "## Raw runs\n\n"
    "| Backdrop | Run | Terminal ms | Terminal gap ms | Upload bytes | UI load ms | Workbench open ms | UI stream ms | UI gap ms |\n"
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|\n"
)

foreach(backdrop IN LISTS backdrops)
    unset(terminal_values)
    unset(terminal_gap_values)
    unset(upload_values)
    unset(ui_load_values)
    unset(workbench_open_values)
    unset(ui_stream_values)
    unset(ui_gap_values)

    foreach(run RANGE 1 ${RUN_COUNT})
        set(terminal_file "${OUTPUT_ROOT}/performance-${backdrop}/run-${run}/terminal-performance.json")
        set(ui_file "${OUTPUT_ROOT}/performance-ui-${backdrop}/run-${run}/ui-performance.json")
        if(NOT EXISTS "${terminal_file}" OR NOT EXISTS "${ui_file}")
            message(FATAL_ERROR "Missing performance evidence for ${backdrop} run ${run}")
        endif()
        file(READ "${terminal_file}" terminal_json)
        file(READ "${ui_file}" ui_json)

        read_json_value(terminal_completed "${terminal_json}" scenario completed)
        read_json_value(ui_completed "${ui_json}" stream completed)
        read_json_value(ui_reopened "${ui_json}" workbench reopened)
        if(NOT terminal_completed OR NOT ui_completed OR NOT ui_reopened)
            message(FATAL_ERROR "Incomplete performance evidence for ${backdrop} run ${run}")
        endif()

        read_json_value(alpha_bits "${terminal_json}" environment alphaBufferBits)
        read_json_value(dwm_type "${terminal_json}" environment dwmBackdropType)
        read_json_value(terminal_ms "${terminal_json}" scenario completionMs)
        read_json_value(terminal_gap "${terminal_json}" scenario maximumHeartbeatGapMs)
        read_json_value(uploaded_bytes "${terminal_json}" terminalRenderer uploadedBytes)
        read_json_value(ui_load_ms "${ui_json}" startup qmlLoadMs)
        read_json_value(workbench_open_ms "${ui_json}" workbench openMs)
        read_json_value(ui_stream_ms "${ui_json}" stream durationMs)
        read_json_value(ui_gap "${ui_json}" stream maximumHeartbeatGapMs)

        if(backdrop STREQUAL "acrylic")
            set(expected_dwm 3)
        elseif(backdrop STREQUAL "mica")
            set(expected_dwm 2)
        elseif(backdrop STREQUAL "micaAlt")
            set(expected_dwm 4)
        else()
            set(expected_dwm 1)
        endif()
        if(NOT dwm_type EQUAL expected_dwm)
            message(FATAL_ERROR "Unexpected DWM backdrop for ${backdrop}: ${dwm_type}, expected ${expected_dwm}")
        endif()
        if(backdrop STREQUAL "opaque")
            if(alpha_bits GREATER 0)
                message(FATAL_ERROR "Opaque diagnostic surface still has ${alpha_bits} alpha bits")
            endif()
        elseif(alpha_bits LESS_EQUAL 0)
            message(FATAL_ERROR "Translucent ${backdrop} surface has no alpha buffer")
        endif()

        list(APPEND terminal_values ${terminal_ms})
        list(APPEND terminal_gap_values ${terminal_gap})
        list(APPEND upload_values ${uploaded_bytes})
        list(APPEND ui_load_values ${ui_load_ms})
        list(APPEND workbench_open_values ${workbench_open_ms})
        list(APPEND ui_stream_values ${ui_stream_ms})
        list(APPEND ui_gap_values ${ui_gap})
        string(APPEND raw_rows
            "| ${backdrop} | ${run} | ${terminal_ms} | ${terminal_gap} | ${uploaded_bytes} | ${ui_load_ms} | ${workbench_open_ms} | ${ui_stream_ms} | ${ui_gap} |\n"
        )
    endforeach()

    median(terminal_median ${terminal_values})
    median(terminal_gap_median ${terminal_gap_values})
    median(upload_median ${upload_values})
    median(ui_load_median ${ui_load_values})
    median(workbench_open_median ${workbench_open_values})
    median(ui_stream_median ${ui_stream_values})
    median(ui_gap_median ${ui_gap_values})
    math(EXPR uploaded_mib "(${upload_median} + 524288) / 1048576")
    file(APPEND "${report}"
        "| ${backdrop} | ${alpha_bits} | ${dwm_type} | ${terminal_median} | ${terminal_gap_median} | ${uploaded_mib} | ${ui_load_median} | ${workbench_open_median} | ${ui_stream_median} | ${ui_gap_median} |\n"
    )
endforeach()

file(APPEND "${report}" "\n${raw_rows}")
message(STATUS "Composition performance matrix: ${report}")
